@extends('frontend.layouts.master')
@section('content')
    @include('frontend.layouts.sections.hero')
    @include('frontend.layouts.sections.why')
    @include('frontend.layouts.sections.arrival')
    @include('frontend.layouts.sections.products')
    @include('frontend.layouts.sections.subscribe')
    @include('frontend.layouts.sections.client')
@endsection